name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make unix
      run: make unix
    - name: make windows
      run: make windows
    - name: build windows
      run: make windows_build
    - name: clean
      run: make clean
