name: Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-App:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-mingw@v2
    
    - name: build unix
      run: make unix unix_build
    - name: build windows
      run: make windows windows_build
    - name: clean
      run: make clean
